<?php

namespace App\Http\Controllers;

use DeepCopy\Filter\KeepFilter;
use Illuminate\Http\Request;
use Illuminate\Validation\Rules\Password;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Illuminate\Support\Facades\Auth;
use App\Models\User;


class AuthController extends Controller
{

    /**
     * Register a new user.
     * Validates the incoming request, creates the user, and starts a session.
     *
     * @param Request $request
     * @return JsonResponse
     */

    public function register(Request $request): JsonResponse
    {

        //validate the registration credentials
        $data = $request->validate([
            'email' => 'required|string|email|max:255|unique:users,email',
            'password' => ['required', 'confirmed', Password::min(8)],
            'title' => 'required|in:Úr,Hölgy, Dr., Professzor',
            'first_name' => 'required|string|max:100',
            'last_name' => 'required|string|max:100',
        ]);

        // Log in the newly created user and regenerate the session
        $user = User::create($data);

        // Create the user in the database with the validated data (id is auto-generated by the database)
        Auth::login($user);

        //csrf token,  Regenerate the session to prevent session fixation attacks
        $request->session()->regenerate();

        //returns the user data and a 201 created status code
        return response()->json(['user' => $user], 201);
    }


    /**
     * It's a login request
     * Authenticate an existing user.
     * Validates credentials, attempts login, and regenerates the session.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function login(Request $request): JsonResponse
    {

        //validates the login credentials
        $request->validate([
            'email' => 'required|email',
            'password' => 'required|string',
        ]);

        // If authentication fails, throw a validation exception
        if (!Auth::attempt($request->only('email', 'password'))) {
            throw ValidationException::withMessages([
                'email' => ['The credentials you provided did not match our records.'],
            ]);
        }

        //else: starts the session, regenerates the session to prevent session fixation attacks
        $request->session()->regenerate();

        return response()->json(['user' => $request->user()]);
    }
    // Regenerates (terminates) the session to prevent session fixation attacks, generates a new csrf token
    public function logout(Request $request) : JsonResponse
    {

        $request->user()->currentAccessToken()->delete();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return response()->json(['message' => 'Logged-out successfully.']);

    }

    /**
     * Return the authenticated user's data.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function me(Request $request) : JsonResponse
    {
        return response()->json($request->user());
    }



}
